[versions]
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
kotlin-wrappers = "2026.5.6"
agp = "9.2.1"
android-compileSdk = "36"
android-minSdk = "24"
bcrypt = "0.10.2"
kotlincrypto-hash = "0.8.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-wrapper-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
kotlincrypto-hash-sha2 = { module = "org.kotlincrypto.hash:sha2", version.ref = "kotlincrypto-hash" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }